<#

    .SYNOPSIS
        Starts the EnvironmentDiscoveryUtility module.

    .DESCRIPTION
        Provide a simple entry point to the Environment Discovery Utility without having to manually import modules.

    .PARAMETER Modules
        An array of strings indicating which modules the Environment Discovery Utility should run.  This defaults to 'All'

    .PARAMETER OutputFolder
        A string to designate the file path to place all files generated by EDU. This defaults to the Users desktop file location

    .OUTPUTS
        A JSON representation of the discovered environment.

    .EXAMPLE
        Invoke-Discovery -Modules All -OutputFolder c:\temp

    .EXAMPLE
        Invoke-Discovery -Modules Exchange,AD -OutputFolder c:\temp

    .EXAMPLE
        Invoke-Discovery -Modules Exchange,AD -OutputFolder c:\temp -SkipDnsLookups

#>

[CmdletBinding()]
param (
    # An array of strings indicating which modules the Environment Discovery Utility should run.  Possible values: AD, Exchange, All.  This defaults to "All"
    [ValidateSet("ad","exchange","all")]
    [array]
    $Modules = @("all"),

    # A string to designate the file path to place all files generated by EDU. This defaults to the Users desktop file location
    [string]
    $OutputFolder = "$((Get-Location).Path)",
    
    # Switch used to skip performing DNS lookups
    [switch]
    $SkipDnsLookups
)

Import-Module .\EnvironmentDiscoveryUtility.psd1 -Force

Start-EnvironmentDiscovery -Modules $Modules -OutputFolder $OutputFolder -Verbose:$VerbosePreference -Debug:$DebugPreference -SkipDnsLookups:$SkipDnsLookups
